import type { ThemeConfig, ThemeId } from "./types";

export const THEMES: Record<ThemeId, ThemeConfig> = {
  marigold: {
    id: "marigold",
    name: "Royal Marigold",
    tagline: "One simple grain of milk rice, and the cake of serpents. Splendour in saffron.",
    emoji: "🏵️",
    bg: ["#3b1507", "#7c2506", "#c4510f"],
    bgDeep: "#2a0e04",
    accent: "#ff9d2e",
    accentSoft: "#ffc266",
    text: "#fff6e9",
    textSoft: "#ffd9a0",
    gold: "#ffd97a",
    ui: {
      btn: "from-orange-500 to-amber-500",
      btnText: "text-white",
      card: "bg-[#2a0e04]/70",
    },
  },
  peacock: {
    id: "peacock",
    name: "Peacock Paisley",
    tagline: "A peacock blooms where love sails upon turquoise.",
    emoji: "🦚",
    bg: ["#031b1f", "#063f47", "#0d6b70"],
    bgDeep: "#02121a",
    accent: "#2bd4c8",
    accentSoft: "#8be9df",
    text: "#eefcfa",
    textSoft: "#b6f3ec",
    gold: "#ffce6b",
    ui: {
      btn: "from-teal-500 to-cyan-500",
      btnText: "text-white",
      card: "bg-[#02121a]/70",
    },
  },
  diya: {
    id: "diya",
    name: "Diya Twilight",
    tagline: "Lamps adrift — every flame is a wish your sister made.",
    emoji: "🪔",
    bg: ["#16091f", "#3b1049", "#6b1f5e"],
    bgDeep: "#0e0517",
    accent: "#ff8a5c",
    accentSoft: "#ffc29e",
    text: "#fff0e8",
    textSoft: "#ffcbb2",
    gold: "#ffd97a",
    ui: {
      btn: "from-purple-500 to-fuchsia-500",
      btnText: "text-white",
      card: "bg-[#0e0517]/70",
    },
  },
  rose: {
    id: "rose",
    name: "Rose Garden",
    tagline: "Soft petals for the sister who grew into every sunrise.",
    emoji: "🌹",
    bg: ["#2b0a12", "#5c1128", "#8f2340"],
    bgDeep: "#1e060d",
    accent: "#ff7ba9",
    accentSoft: "#ffb3cf",
    text: "#fff2f5",
    textSoft: "#ffd3e0",
    gold: "#ffd97a",
    ui: {
      btn: "from-rose-500 to-pink-500",
      btnText: "text-white",
      card: "bg-[#1e060d]/70",
    },
  },
  cosmic: {
    id: "cosmic",
    name: "Cosmic Stars",
    tagline: "Brother & sister — the two stars that bound the galaxy.",
    emoji: "✨",
    bg: ["#050514", "#101040", "#26307a"],
    bgDeep: "#030310",
    accent: "#7da2ff",
    accentSoft: "#b7c9ff",
    text: "#eef1ff",
    textSoft: "#c7d4ff",
    gold: "#ffd97a",
    ui: {
      btn: "from-indigo-500 to-blue-500",
      btnText: "text-white",
      card: "bg-[#030310]/70",
    },
  },
  jewel: {
    id: "jewel",
    name: "Royal Jewel",
    tagline: "Emerald, gold and a bond more precious than either.",
    emoji: "💎",
    bg: ["#04130d", "#0a3a24", "#11573a"],
    bgDeep: "#02100a",
    accent: "#37e293",
    accentSoft: "#93f4c6",
    text: "#eaffe9",
    textSoft: "#c4f4d8",
    gold: "#ffd97a",
    ui: {
      btn: "from-emerald-500 to-green-500",
      btnText: "text-white",
      card: "bg-[#02100a]/70",
    },
  },
  mehndi: {
    id: "mehndi",
    name: "Mehndi Dawn",
    tagline: "Henna swirls and warm hands — a sister's language of love.",
    emoji: "🌿",
    bg: ["#241505", "#4d2a08", "#8a4b0e"],
    bgDeep: "#180d02",
    accent: "#ffc46b",
    accentSoft: "#ffe3ad",
    text: "#fff8ea",
    textSoft: "#ffe8c2",
    gold: "#fff0c2",
    ui: {
      btn: "from-amber-500 to-orange-600",
      btnText: "text-white",
      card: "bg-[#180d02]/70",
    },
  },
  confetti: {
    id: "confetti",
    name: "Festival Confetti",
    tagline: "Confetti for the festival, cake for the bond.",
    emoji: "🎊",
    bg: ["#170a2b", "#4a1e6b", "#8f3f8f"],
    bgDeep: "#10051f",
    accent: "#ff6b9d",
    accentSoft: "#ffa3c4",
    text: "#fff4fa",
    textSoft: "#ffd4e6",
    gold: "#ffe08a",
    ui: {
      btn: "from-fuchsia-500 to-purple-500",
      btnText: "text-white",
      card: "bg-[#10051f]/70",
    },
  },
};

export const THEME_LIST = Object.values(THEMES);
